package services.configuration

import services.actors.support.{EventsourcedExtension, ConfigurableEventsourcedProcessorsProvider, HasSystem}

trait DefaultEventsourcedProcessorsProvider extends ConfigurableEventsourcedProcessorsProvider
with DefaultActorsConfiguration
with HasSystem
with EventsourcedExtension